const router = require('express').Router();
const { protect } = require('../middleware/auth');
const { myRequests, receivedRequests, reviewRequest, cancelRequest, agreeContract, getContract } = require('../controllers/adoptionController');
router.use(protect);
router.get('/mine',         myRequests);
router.get('/received',     receivedRequests);
router.patch('/:id',        reviewRequest);
router.patch('/:id/cancel', cancelRequest);
router.post('/:id/agree-contract', agreeContract);
router.get('/:id/contract', getContract);
module.exports = router;
